- hosts: localhost
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: dilan_aws
         group: test
         instance_type: t2.micro
         aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
         aws_secret_key": "{{env `AWS_SECRET_KEY_ID`}}"
         image: "{{ ami_id }}"
         wait: true
         exact_count: 5
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2
